### ISSUE TITLE
Restrict access to the Kubernetes Service Management API

### ISSUE THREAD

**Issue by hmc-berk** [zachChilders/just-add-water#68]
Restrict access to the Kubernetes Service Management API by granting API access only to IP addresses in specific ranges. It is recommended to limit access to authorized IP ranges to ensure that only applications from allowed networks can access the cluster.

**Comment by hmc-berk** [comment]
+ Additional Action Item: IP forwarding on your virtual machine should be disabled (Preview

**Comment by zachChilders** [comment]
We lock down our clusters with AAD RBAC already.  Was this an Azure suggestion?  Our management plane is Azure hosted so I don't know that we can lock its networking down without holding the whole instance.

**Comment by zachChilders** [comment]
I don't think we have a safe way to do this.  We need ip ranges from Azure, which update frequently, plus we need to add our own clients, which is nontrivial since we don't all share a common VPN.  

I'll leave this link here in case we want to do it in the future: https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges

There's a terraform config for this as well: https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#api_server_authorized_ip_ranges
